baseURL = "https://blog.parloapp.io"
languageCode = 'en-us'
title = 'Parlo App'
theme = ''
googleAnalytics = ""

[params]
    description = 'The fun, easy, and interactive way to learn French—practice speaking, reading, and growing your skills one conversation at a time!'
    favicon = "/images/favicon.ico"

[taxonomies]
  category = "categories"
  tag = "tags"

[author.social]
  facebook = ""
  github = ""
  twitter = ""

[permalinks]
  page = "/:slug/"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about"
    [[menu.main]]
        name = "Blog"
        url = "/blog"